export const examples = [
    { "text": "input: #5 MOD composite" },
    { "text": "output: #5 - 3 Surface Posterior Composite Filling" },
    { "text": "input: #8 DOB5 composite" },
    { "text": "output: #8 - 3 Surface Anterior Composite Filling" },
    { "text": "input: #12 MO5 composite" },
    { "text": "output: Error: #12 MO5 Composite is not a valid treatment option. Class 5 fillings can only be treatment planned for Buccal (B) or Lingual (L) surfaces." },
    { "text": "input: #7 DO composite\n#9 MOB5 composite\n#12 DOL/5 composite" },
    { "text": "output: #7 - 2 Surface Anterior Composite Filling\n#9 - 3 Surface Anterior Composite Filling\n#12 - 3 Surface Posterior Composite Filling" },
    { "text": "input: #6 needs a mod filling" },
    { "text": "output: Error: \" #6 needs a mod filling \" Filling type not specified." },
    { "text": "input: #4 mod" },
    { "text": "output: Error: \" #4 mod \" Filling type not specified." },
    { "text": "input: #11 MOB5L5 comp" },
    { "text": "output: #11 - 4 Surface Anterior Composite Filling" },
    { "text": "input: #10 MB5L-5 amalga" },
    { "text": "output: #10 - 3 Surface Anterior Amalgam Filling" },
    { "text": "input: #9 MB(V)L(V) comp" },
    { "text": "output: #9 - 3 Surface Anterior Composite Filling" },
    { "text": "input: #22 MOB-5L-5 comp" },
    { "text": "output: #22 - 4 Surface Anterior Composite Filling" },
    { "text": "input: #24 MB-5L-5 amal" },
    { "text": "output: #24 - 3 Surface Anterior Amalgam Filling" },
    { "text": "input: #1 MOD comp\n#3 DO comp\n#6 MOB/5L/5 amalg" },
    { "text": "output: #1 - 3 Surface Posterior Composite Filling\n#3 - 2 Surface Anterior Composite Filling\n#6 - 4 Surface Anterior Amalgam Filling" },
    { "text": "input: #6 PFM crown" },
    { "text": "output: #6 - PFM Crown" },
    { "text": "input: #22 acc cronw" },
    { "text": "output: #22 - ACC Crown" },
    { "text": "input: #5 MOD comp\n#6 PFM crown\n#12 ACC crown" },
    { "text": "output: #5 - 3 Surface Posterior Composite Filling\n#6 - PFM Crown\n#12 - ACC Crown" },
    { "text": "input: #5 needs a root canl" },
    { "text": "output: #5 - Root Canal Pre-Molar" },
    { "text": "input: #6 needs a root canal" },
    { "text": "output: #6 - Root Canal Pre-Molar" },
    { "text": "input: #19 needs a root canal" },
    { "text": "output: #19 - Root Canal Molar" },
    { "text": "input: #22 RCT" },
    { "text": "output: #22 - Root Canal Anterior" },
    { "text": "input: #1 rct" },
    { "text": "output: #1 - Root Canal Molar" },
    { "text": "input: #24 rct" },
    { "text": "output: #24 - Root Canal Anterior" },
    { "text": "input: #23 rct" },
    { "text": "output: #23 - Root Canal Anterior" },
    { "text": "input: #12 RCT" },
    { "text": "output: #12 - Root Canal Pre-Molar" },
    { "text": "input: #25 rct" },
    { "text": "output: #25 - Root Canal Anterior" },
    { "text": "input: #28 rct" },
    { "text": "output: #28 - Root Canal Pre-Molar" },
    { "text": "input: #6 rct" },
    { "text": "output: #6 - Root Canal Anterior" },
    { "text": "input: #8 rct" },
    { "text": "output: #8 - Root Canal Anterior" },
    { "text": "input: #9 RCT" },
    { "text": "output: #9 - Root Canal Anterior" },
    { "text": "input: #11 RCT" },
    { "text": "output: #11 - Root Canal Anterior" },
    { "text": "input: #16 rct" },
    { "text": "output: #16 - Root Canal Molar" },
    { "text": "input: #15 rct" },
    { "text": "output: #15 - Root Canal Molar" },
    { "text": "input: #5 pfm crn\n#6 RCT, acc" },
    { "text": "output: #5 - PFM Crown\n#6 - Root Canal Anterior, ACC Crown" },
    { "text": "input: #15 build up" },
    { "text": "output: #15 - Build Up w/o Post" },
    { "text": "input: #1 build up with post" },
    { "text": "output: #1 - Build Up w/ Post" },
    { "text": "input: #5 core bu" },
    { "text": "output: #5 - Build Up w/o Post" },
    { "text": "input: #22 BU" },
    { "text": "output: #22 - Build Up w/o Post" },
    { "text": "input: #12 RCT + BU, acc" },
    { "text": "output: #12 - Root Canal Pre-Molar, Build Up w/o Post, ACC Crown" },
    { "text": "input: #22 needs a root canal with post and core, acc" },
    { "text": "output: #22 - Root Canal Anterior, Build Up w/ Post, ACC Crown" },
    { "text": "input: #12 needs a RCT with post + bu, acc" },
    { "text": "output: #12 - Root Canal Pre-Molar, Build Up w/ Post, ACC Crown" },
    { "text": "input: #15 rct - bu-post" },
    { "text": "output: #15 - Root Canal Molar, Build Up w/ Post" },
    { "text": "input: #12 rct w/post BU and pfm" },
    { "text": "output: #12 - Root Canal Pre-Molar, Build Up w/ Post, PFM Crown" },
    { "text": "input: #14 cbct" },
    { "text": "output: #14 - Maxillary CBCT" },
    { "text": "input: upper and lower cbct" },
    { "text": "output: Upper and Lower CBCT" },
    { "text": "input: #12-14 acc bridge" },
    { "text": "output: #12 - ACC Retainer Crown\n#13 - ACC Pontic\n#14 - ACC Retainer Crown" },
    { "text": "input: #13-15 pfm bridge" },
    { "text": "output: #13 - PFM Retainer Crown\n#14 - PFM Pontic\n#15 - PFM Retainer Crown" },
    { "text": "input: #22-27 acc bridge" },
    { "text": "output: #22 - ACC Retainer Crown\n#23 - ACC Pontic\n#24 - ACC Pontic\n#25 - ACC Pontic\n#26 - ACC Pontic\n#27 - ACC Retainer Crown" },
    { "text": "input: #22 rct, core build up, post, acc crown\n#23 pontic\n#24 acc crown" },
    { "text": "output: #22 - Root Canal Anterior, Build Up w/ Post, ACC Retainer Crown\n#23 - ACC Pontic\n#24 - ACC Retainer Crown" },
    { "text": "input: #7 rct, build up, pfm crown\n#8 pontic\n#9 pfm" },
    { "text": "output: #7 - Root Canal Anterior, Build Up w/o Post, PFM Retainer Crown\n#8 - ACC Pontic\n#9 - PFM Retainer Crown" },
    { "text": "input: #12 acc" },
    { "text": "output: #12 - ACC Crown" },
    { "text": "input: #15 acc\n#16 pontic\n#17 acc" },
    { "text": "output: #15 - ACC Retainer Crown\n#16 - ACC Pontic\n#17 - ACC Retainer Crown" },
    { "text": "input: #14 acc\n#15 acc \n#16 acc" },
    { "text": "output: #14 - ACC Crown\n#15 - ACC Crown\n#16 - ACC Crown" },
    { "text": "input: #12 bridge" },
    { "text": "output: Error: \" #12 bridge \" is not a valid treatment option. Please specify which teeth are retainer crowns and which are pontics." },
    { "text": "input: #22-24 bridge" },
    { "text": "output: Error: \" #22-24 bridge \" Please specify material type: ACC, PFM, or FMC." },
    { "text": "input: #3 rct, build up, pfm\n#4 pontic\n#5 pfm" },
    { "text": "output: #3 - Root Canal Anterior, Build Up w/o Post, PFM Retainer Crown\n#4 - FMC Pontic\n#5 - FMC Retainer Crown" },
    { "text": "input: #12-15 acc fpd" },
    { "text": "output: #12 - ACC Retainer Crown\n#13 - ACC Pontic\n#14 - ACC Pontic\n#15 - ACC Retainer Crown" },
    { "text": "input: #12-15 fpd" },
    { "text": "output: Error: \" #12-15 fpd \" Please specify material type: ACC, PFM, or FMC." },
    { "text": "input: #2 MOD comp\n#3 DO comp\n#4 rct, build up, acc retainer crown\n#5 pontic\n#6 acc retainer crown" },
    { "text": "output: #2 - 3 Surface Posterior Composite Filling\n#3 - 2 Surface Anterior Composite Filling\n#4 - Root Canal Pre-Molar, Build Up w/o Post, ACC Retainer Crown\n#5 - ACC Pontic\n#6 - ACC Retainer Crown" },
    { "text": "input: #4 DO com\n#15 MOD amalg\n#22 rct build up retainer crown\n#23 pontic\n#24 retainer crown" },
    { "text": "output: #4 - 2 Surface Anterior Composite Filling\n#15 - 3 Surface Posterior Amalgam Filling\nError: \" #22 rct build up retainer crown \" Please specify material type: ACC, PFM, or FMC.\nError: \" #23 pontic \" Please specify material type: ACC, PFM, or FMC.\nError: \" #24 retainer crown \" Please specify material type: ACC, PFM, or FMC." },
    { "text": "input: #22 rct build up retainer crown\n#23 pontic\n#24 retainer crown" },
    { "text": "output: Error: \" #22 rct build up retainer crown \" Please specify material type: ACC, PFM, or FMC.\nError: \" #23 pontic \" Please specify material type: ACC, PFM, or FMC.\nError: \" #24 retainer crown \" Please specify material type: ACC, PFM, or FMC." },
    { "text": "input: #22 rct build up \n22-24 bridge" },
    { "text": "output: #22 - Root Canal Anterior, Build Up w/o Post\nError: \" #22-24 bridge \" Please specify material type: ACC, PFM, or FMC." },
    { "text": "input: #12 implant" },
    { "text": "output: #12 - Single Implant" },
    { "text": "input: #12-13, #22-23 implants w/acc" },
    { "text": "output: #12 - Single Implant, Implant Supported ACC Retainer Crown\n#13 - Single Implant, Implant Supported ACC Retainer Crown\n#22 - Single Implant, Implant Supported ACC Retainer Crown\n#23 - Single Implant, Implant Supported ACC Retainer Crown" },
    { "text": "input: #12-15 implant bridge w/acc" },
    { "text": "output: #12 - Single Implant, Implant Supported ACC Retainer Crown\n#13 - ACC Pontic\n#14 - ACC Pontic\n#15 - Single Implant, Implant Supported ACC Retainer Crown" },
    { "text": "input: #7-9 implant bridge" },
    { "text": "output: Error: \" #7-9 implant bridge \" Please specify Implant Crown material type: ACC or PFM." },
    { "text": "input: #9-11 implant bridge with acc crowns" },
    { "text": "output: #9 - Single Implant, Implant Supported ACC Retainer Crown\n#10 - ACC Pontic\n#11 - Single Implant, Implant Supported ACC Retainer Crown" },
    { "text": "input: #12 ext surgical" },
    { "text": "output: #12 - Surgical Extraction" },
    { "text": "input: #15 ext" },
    { "text": "output: Error: \" #15 ext \" Please specify extraction type: Surgical or Routine." },
    { "text": "input: Upper denture" },
    { "text": "output: Upper Denture" },
    { "text": "input: Lower denture" },
    { "text": "output: Lower Denture" },
    { "text": "input: extractions" },
    { "text": "output: Error: \" extractions \" Please specify which teeth need extractions." },
    { "text": "input: #12-15 extractions" },
    { "text": "output: Error: \" #12-15 extractions \" Please specify extraction type: Surgical or Routine." },
    { "text": "input: #12-14 single implant with crown" },
    { "text": "output: Error: \" #12-14 \" single implant with crown \" Please specify Implant Crown material type: ACC or PFM." },
    { "text": "input: #3-5 single implants with crown" },
    { "text": "output: Error: \" #3-5 single implants with crown \" Please specify Implant Crown material type: ACC or PFM." },
    { "text": "input: #7-11 single implants with pfm crown" },
    { "text": "output: #7 - Single Implant, Implant Supported PFM Crown\n#8 - Single Implant, Implant Supported PFM Crown\n#9 - Single Implant, Implant Supported PFM Crown\n#10 - Single Implant, Implant Supported PFM Crown\n#11 - Single Implant, Implant Supported PFM Crown" },
    { "text": "input: #9-11 implant bridge with pfm crowns" },
    { "text": "output: #9 - Single Implant, Implant Supported PFM Retainer Crown\n#10 - PFM Pontic\n#11 - Single Implant, Implant Supported PFM Retainer Crown" },
    { "text": "input: exts #7-11 with upper denture" },
    { "text": "output: Error: \" exts #7-11 with upper denture \" Please specify extraction type: Surgical or Routine.\nUpper Denture" },
    { "text": "input: #12-17 surgical extractsions with upper denture" },
    { "text": "output: #12 - Surgical Extraction\n#13 - Surgical Extraction\n#14 - Surgical Extraction\n#15 - Surgical Extraction\n#16 - Surgical Extraction\n#17 - Surgical Extraction\nUpper Denture" },
    { "text": "input: maxillary denture" },
    { "text": "output: Upper Denture" },
    { "text": "input: mandibular denture" },
    { "text": "output: Lower Denture" },
    { "text": "input: upper cbct" },
    { "text": "output: Maxillary CBCT" },
    { "text": "input: lower cbct" },
    { "text": "output: Mandibular CBCT" },
    { "text": "input: " },
    { "text": "output: " }
];