import { createContext } from 'react';

export const BusinessContext = createContext({
    businessName: '',
    setBusinessName: () => { },
    isUserLoggedIn: false,
    setIsUserLoggedIn: () => { },
    patients: [],
    setPatients: () => { },
    facilityCdtCodes: [],
    setFacilityCdtCodes: () => { },
    defaultCdtCodes: [],
    setDefaultCdtCodes: () => { },
    searchQuery: '',
    setSearchQuery: () => { },
    filteredPatients: [],
    setFilteredPatients: () => { },
    selectedPatient: null, 
    setSelectedPatient: () => { },
    payers: [],
    setPayers: () => { },
    facilityPayerCdtCodeFees: [],
    setFacilityPayerCdtCodeFees: () => { },
    //activeCdtCodes: [],
    //setActiveCdtCodes: () => { },
});
